- name: Deploy to Tomcat
  copy:
       src: "../files/java-hello-world-webapp-{{ artifact_version }}.war"
       dest: /opt/apache-tomcat-7.0.61/webapps/

- name: Restart Tomcat Service
  service:
          name: tomcat
          state: restarted