- name: Download an artifact from a private repository requiring authentication
  maven_artifact:
      group_id: org.cloudifysource.examples
      artifact_id: java-hello-world-webapp
      repository_url: 'http://10.128.0.15:8081/repository/maven-nexus/'
      username: jenkins
      password: Jenkins@123
      dest: ../files/
      extension: war
      version: "{{ artifact_version }}"
- name: Deploy to Tomcat
  hosts: tomcat-servers
  tasks:
        - name: Upload file to Tomcat machine
          copy:
               src: ../files/*.war
               dest: /opt/apache-tomcat-7.0.61/webapps/
  